### ISSUE TITLE
Awesome idea! but boogi-cli not working for me :(  please help! 

### ISSUE THREAD

**Issue by catalina-cimpanu** [filipowm/boogi-cli#21]
Hi!
I just found boogi on the gatsby website (in starters) and I thought is such a nice idea, it also looks really neat too, so I said I'd give it a try. 
So I installed boogi-cli globally and ran boogi init, but unfortunately it doesn't work.

Is there something I'm doing wrong?... Did I forget anything? 
Please help me. I also downloaded the files from [here](https://github.com/filipowm/BooGi) but it's been half an hour and gatsby is still building schema :(

I tried both v 1.0.1and 1.0.0.

Thank you in advance!

Here's the console output:
```
catal@Catalina MINGW64 ~/Catalina/Learning stuff/Web development/Experiments/boogi-experiments/zaBoogie
$ boogi init
______                _____  _ 
| ___ \              |  __ \(_)
| |_/ /  ___    ___  | |  \/ _ 
| ___ \ / _ \  / _ \ | | __ | |
| |_/ /| (_) || (_) || |_\ \| |
\____/  \___/  \___/  \____/|_|


  √ � Checking if BooGi is already initialized in .
  √ � Creating required directories
  √ � Preparing Git repo
  √ �‍♀️ Now configuration wizard will help you set up BooGi
? Select BooGi version to use: v1.0.0


Before start...

Now wizard will walk you through a series of questions helping you set up your BooGi app.
For details or help visit our docs (​https://boogi.netlify.app/configuration/setting-up​).

You are using basic wizard. You will be guided to set up most important settings, for the rest defaults are applied.
If you want to use full mode, add --full option to init command.
You will be able to change any configuration at any time after initialization!

If you are not able to provide some configuration right away -- you can just skip it by pressing enter.
Default values are visible in gray color in (brackets). You can accept them by pressing enter.

Page Info
While creating your own BooGi-based page, you should first set up metadata.
It defines core information about your page required for it to work, its identification and SEO.
? [required] Name of your page: skizzo world
? [required] Short name (e.g. abbreviation) of your page: skizzos
? Description of your website. Used to improve website SEO. the home of skizzos
? [required] Language of your website: English
? [required] Full URL to your website, e.g. https://mysite.com: http://localhost

Progressive Web App
PWA is a web app that uses modern web capabilities to deliver an app-like experience to users.
We recommend enabling it cause it greatly improves user experience!
? Do you want to enable PWA? (recommended) Yes

Header
Set up app header
? [required] Do you want to enable page header? Yes

Sidebar
Set up app navigation sidebar. You will be able to manage groups and advanced configuration later on.
? [required] Do you want to enable navigation sidebar? Yes

Social
Set up social buttons displayed in header. They allow you to link easily other social pages to your BooGi app.
? Do you want to configure social buttons? Yes
? Which social buttons you want to configure? github
? Provide link to github: https://github.com/catalina-cimpanu

Search
Set up app search capabilities. As of now only Algolia search is supported (local search is coming soon)
? [required] Do you want to enable Algolia search? Yes
? Which component should be used in header to initiate search? Search icon
? Should search pagination be enabled? (recommended) Yes

RSS feed
Set up RSS feed.
? Do you want to enable RSS feed? Yes

App features
Set up additional app features.
? In which repository do you keep this app? None of the above    
? Do you want to enable dark mode (light/dark theme mode)? Yes
? Should dark theme be the default theme? No

  × ⚡ Creating files
    → ENOENT: no such file or directory, scandir '/assets/templates'
    ⚙️  Applying configuration
    � Downloading required dependencies
    Making first commit
ENOENT: no such file or directory, scandir '/assets/templates'

� Done! You can not start your app with boogi develop or build it with boogi build �

catal@Catalina MINGW64 ~/Catalina/Learning stuff/Web development/Experiments/boogi-experiments/zaBoogie (master)
$ boogi develop
______                _____  _
| ___ \              |  __ \(_)
| |_/ /  ___    ___  | |  \/ _
| ___ \ / _ \  / _ \ | | __ | |
| |_/ /| (_) || (_) || |_\ \| |
\____/  \___/  \___/  \____/|_|


  × ⚡ Verifying app...
    → BooGi is not initialized in this directory. Run boogi init first
    Downloading BooGi ...
    � Downloading requirements...
    � Starting development server on port 8000
BooGi is not initialized in this directory. Run boogi init first
(node:11132) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at C:\Users\catal\AppData\Roaming\npm\node_modules\boogi-cli\lib\commands\develop\develop.js:33:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

catal@Catalina MINGW64 ~/Catalina/Learning stuff/Web development/Experiments/boogi-experiments/zaBoogie (master)
$
```

**Comment by filipowm** [comment]
Hi there,

I just release v0.4.0, hopefully fixing this issue. Please update and try again. If it won't work, just let me know. I'll investigate it further today/

**Comment by catalina-cimpanu** [comment]
Hi !
I ran again `npm install -g boogi-cli` so that i have the latest boogi-cli, deleted everything in the folder I want to install boogi, then ran `boogi init` in this folder, but I'm getting the same error as yesterday.
I don't have v0.4.0 as an option when choosing the version, is that normal?

Thank you again :)

Here's the output in the console:
```
catal@Catalina MINGW64 ~/Catalina/Learning stuff/Web development/Experiments/boogi-experiments/zaBoogie
$ boogi init
______                _____  _
| ___ \              |  __ \(_)
| |_/ /  ___    ___  | |  \/ _
| ___ \ / _ \  / _ \ | | __ | |
| |_/ /| (_) || (_) || |_\ \| |
\____/  \___/  \___/  \____/|_|


  √ � Checking if BooGi is already initialized in .
  √ � Creating required directories
  √ � Preparing Git repo
  √ �‍♀️ Now configuration wizard will help you set up BooGi
? Select BooGi version to use: v1.0.1 recommended


Before start...

Now wizard will walk you through a series of questions helping you set up your BooGi app. 
For details or help visit our docs (​https://boogi.netlify.app/configuration/setting-up​).

You are using basic wizard. You will be guided to set up most important settings, for the rest defaults are applied.
If you want to use full mode, add --full option to init command.
You will be able to change any configuration at any time after initialization!

If you are not able to provide some configuration right away -- you can just skip it by pressing enter.
Default values are visible in gray color in (brackets). You can accept them by pressing enter.

Page Info
While creating your own BooGi-based page, you should first set up metadata.
It defines core information about your page required for it to work, its identification and SEO.
? [required] Name of your page: skizzo world
? [required] Short name (e.g. abbreviation) of your page: skizzos
? Description of your website. Used to improve website SEO. the home of skizzos
? [required] Language of your website: English
? [required] Full URL to your website, e.g. https://mysite.com: http://localhost

Progressive Web App
PWA is a web app that uses modern web capabilities to deliver an app-like experience to users.
We recommend enabling it cause it greatly improves user experience!
? Do you want to enable PWA? (recommended) Yes

Header
Set up app header
? [required] Do you want to enable page header? Yes

Sidebar
Set up app navigation sidebar. You will be able to manage groups and advanced configuration later on.
? [required] Do you want to enable navigation sidebar? Yes

Social
Set up social buttons displayed in header. They allow you to link easily other social pages to your BooGi app.
? Do you want to configure social buttons? Yes
? Which social buttons you want to configure? github
? Provide link to github: https://github.com/catalina-cimpanu

Search
Set up app search capabilities. As of now only Algolia search is supported (local search is coming soon)
? [required] Do you want to enable Algolia search? Yes
? Which component should be used in header to initiate search? Search icon
? Should search pagination be enabled? (recommended) Yes

RSS feed
Set up RSS feed.
? Do you want to enable RSS feed? Yes

App features
Set up additional app features.
? In which repository do you keep this app? None of the above    
? Do you want to enable dark mode (light/dark theme mode)? Yes
? Should dark theme be the default theme? No

  × ⚡ Creating files
    → ENOENT: no such file or directory, scandir '/assets/templates'
    ⚙️  Applying configuration
    � Downloading required dependencies
    Making first commit
ENOENT: no such file or directory, scandir '/assets/templates'

� Done! You can not start your app with boogi develop or build it with boogi build �

catal@Catalina MINGW64 ~/Catalina/Learning stuff/Web development/Experiments/boogi-experiments/zaBoogie (master)
$ boogi develop
______                _____  _ 
| ___ \              |  __ \(_)
| |_/ /  ___    ___  | |  \/ _ 
| ___ \ / _ \  / _ \ | | __ | |
| |_/ /| (_) || (_) || |_\ \| |
\____/  \___/  \___/  \____/|_|


  × ⚡ Verifying app...
    → BooGi is not initialized in this directory. Run boogi init first
    Downloading BooGi ...
    � Downloading requirements...
    � Starting development server on port 8000
BooGi is not initialized in this directory. Run boogi init first
(node:6164) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at C:\Users\catal\AppData\Roaming\npm\node_modules\boogi-cli\lib\commands\develop\develop.js:33:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by timothymalcham** [comment]
I tried spinning up a new instance of this, and `0.3.0` still has this issue. I tried bumping the version to `0.4.0` and `0.3.1` (the latest release according to the readme), and rerun `yarn` to install the new package, but I just get this:

```
Couldn't find any versions for "boogi-cli" that matches "0.4.0"
? Please choose a version of "boogi-cli" from this list: (Use arrow keys)
❯ 0.3.0
  0.2.1
  0.2.0
  0.0.1-pre
```

**Comment by filipowm** [comment]
Sorry for waiting. It seemed there was an issue in my deployment workflow. I managed to fix it and now it works as a charm (I've tested it already) 😄 So please check `0.4.0` version now.

Please verify `0.4.0` know and let me know if works now.

@catalina-cimpanu I think you should also initialize it from scratch unfortunately, because there was some issue during `init` phase.

**Comment by catalina-cimpanu** [comment]
Hi! 

Unfortunately, still having the issue. I saw this morning that yarn is also a requirement, so I also installed yarn.
I also cleaned the npm cache (with `npm clean cache -force`, but then also manually - I'm on windows), but still not working. 
If it's working for you, then maybe it's something I'm doing wrong, I just don't figure out what.

Here are screenshots of this morning:

![boogi1](https://user-images.githubusercontent.com/67892765/97272312-fe122c00-1831-11eb-8587-946b82a38e4b.png)

![boogi2](https://user-images.githubusercontent.com/67892765/97272313-feaac280-1831-11eb-8e48-dc05ff7a64e4.png)

![boogi3](https://user-images.githubusercontent.com/67892765/97272307-fce0ff00-1831-11eb-9c60-d477403192a1.png)

![boogi4](https://user-images.githubusercontent.com/67892765/97272310-fd799580-1831-11eb-9b8c-35602ebf5e93.png)

![boogi5](https://user-images.githubusercontent.com/67892765/97272311-fe122c00-1831-11eb-9491-68fac2d96ab4.png)

**Comment by MichaelHazani** [comment]
just encountered this too. fresh install of everything.

**Comment by filipowm** [comment]
I found the issue! That's the problem when one use only Linux systems... 😄 

There is a an issue on Windows with filesystem operations. I'm on it and will do my best to fix it today! Plus I'll finally add debugging messages 😊

**Comment by catalina-cimpanu** [comment]
> I found the issue! That's the problem when one use only Linux systems... 😄
> 
> There is a an issue on Windows with filesystem operations. I'm on it and will do my best to fix it today! Plus I'll finally add debugging messages 😊

Cool! No hurry 😊

**Comment by agataryg** [comment]
Hi there! Getting the same error message as Catalina on windows. Good luck with the fix - your theme looks great and it's so well documented :)

**Comment by toeggel** [comment]
I have the exact same issue. Really would like to use BooGi but I'm getting discouraged when step 1 of the "Quick Start" already fails.

**Comment by tomeczekstecc** [comment]
I'm getting same problem... and the library looks very promising, so any chance some next  days//weeks?

**Comment by FilipJirsak** [comment]
> I'm getting same problem... and the library looks very promising, so any chance some next days/weeks?

You can use this PR: https://github.com/filipowm/boogi-cli/pull/28

**Comment by astrawnuts** [comment]
exact same issue for me too.
