### ISSUE TITLE
Boogi Develop fails with  Couldn't find the "gatsby-plugin-remove-trailing-slashes"

### ISSUE THREAD

**Issue by anddann** [filipowm/boogi-cli#27]
When I set up a new boogi project v1.0.1 using `boogi init` and then execute `boogi develop`the command fails with the exception

```
 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-remove-trailing-slashes" plugin declared in "/Users/***/***".

Tried looking for a local plugin in /Users/***/***/.boogi/v1.0.1/plugins/gatsby-plugin-remove-trailing-slashes.

Tried looking for an installed package in the following paths:
- ...
- ...

not finished open and validate gatsby-configs - 0.188s
Error: Command failed with exit code 1: gatsby develop -p 8000

not finished open and validate gatsby-configs - 0.188s
    at makeError (/usr/local/lib/node_modules/boogi-cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/boogi-cli/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  shortMessage: 'Command failed with exit code 1: gatsby develop -p 8000',
  command: 'gatsby develop -p 8000',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n' +
    ' ERROR #10226  CONFIG\n' +
    '\n' + (same text as above)' +
    '\n' +
    'not finished open and validate gatsby-configs - 0.188s',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}


```

I tried `cd .boogi/v1.0.1 && npm install gatsby-plugin-remove-trailing-slashes` but this had no effect.

Maybe it is not even related to BooGi but to gatsby https://github.com/gatsbyjs/gatsby/issues/11105

**Comment by anddann** [comment]
In my setup npm install did not installed devDependencies.
Executing
`npm config set production false` and npm config set -g production false` before `boogi develop` fixed the issue
